%YAML:1.0

File.version: "1.0"

Camera.type: "PinHole"

Camera1.fx: 1436.89437780124
Camera1.fy: 1442.58498490709
Camera1.cx: 1218.77863491507
Camera1.cy: 1045.77362896196

Camera1.k1: 0.0144210402954516
Camera1.k2: -0.0148287624062537
Camera1.p1: 0.0
Camera1.p2: 0.0
Camera1.k3: 0.0

Camera.width: 2448
Camera.height: 2048

Camera.fps: 10
Camera.RGB: 1

ORBextractor.nFeatures: 4000
ORBextractor.scaleFactor: 1.2
ORBextractor.nLevels: 8
ORBextractor.iniThFAST: 12
ORBextractor.minThFAST: 5

Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -10.0
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 500.0